# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <sc>
  "end.date",
  # <sc>
  "epsilon",
  # <compose_B>
  "mult.x",
  # <compose_B>
  "mult.y",
  # <sc>
  "name",
  # <sc>
  "start.date",
  # <sc>
  "value",
  NULL
))
